#!/usr/bin/env python3
"""Create a deterministic GX12 firmware and CN font release archive.

Example::

    python tools/cn_fonts/package_release.py firmware.bin \
        build/cn_fonts/CN_BASIC.FNT build/release/EdgeTX-GX12-CN.zip
"""

import argparse
import hashlib
import io
import json
from pathlib import Path
import stat
import zipfile

try:
    from . import external_font
except ImportError:  # Direct execution from tools/cn_fonts.
    import external_font


ROOT = Path(__file__).resolve().parents[2]
MANIFEST = Path(__file__).with_name("manifest.json")
FONT_ROOT = ROOT / "radio/src/fonts/cn"
FIXED_TIME = (1980, 1, 1, 0, 0, 0)


def sha256(data):
    return hashlib.sha256(data).hexdigest().upper()


INSTALL_NAME = "安装说明.txt"
CHECKSUM_NAME = "SHA256SUMS.txt"
REQUIRED_LICENSES = {
    "fusion-pixel-font-OFL.txt",
    "unifont-17.0.04-COPYRIGHT.txt",
    "wqy-bitmapfont-GPL.txt",
    "wqy-bitmapfont-README",
    "wqy-bitmapsong-COPYING",
    "wqy-bitmapsong-README",
}


def installation_text(firmware_name):
    return f"""EdgeTX GX12 中文固件安装说明

发布文件
- {firmware_name}：GX12 固件
- CN_BASIC.FNT：中文外置字体
- SHA256SUMS.txt：发布内容校验值

安装步骤
1. 刷写前备份模型和遥控器设置，确认电池电量充足，并用 SHA256SUMS.txt 校验文件。
2. 将 CN_BASIC.FNT 复制到 SD 卡的 /FONTS/CN_BASIC.FNT（目录和文件名须保持一致）。
3. 将 {firmware_name} 复制到 SD 卡的 /FIRMWARE/ 目录。
4. 安全弹出 SD 卡，按 GX12 的正常方式进入 EdgeTX Bootloader。
5. 在 Bootloader 中选择固件写入项，选择 {firmware_name}，按屏幕提示确认并等待写入完成；写入期间不要断电或移除 SD 卡。
6. 写入完成后重启遥控器。若外置字体缺失或校验失败，中文字体不会正常加载。

路径依据：固件源码定义 FIRMWARES_PATH=/FIRMWARE，外置字体默认路径为
/FONTS/CN_BASIC.FNT；Bootloader 固件菜单只列出 .bin 文件并在确认后写入。
""".encode("utf-8")


def _regular_file(path, label):
    path = Path(path)
    if path.is_symlink() or not path.exists() or not stat.S_ISREG(path.stat().st_mode):
        raise ValueError(f"{label} must be a regular file")
    data = path.read_bytes()
    if not data:
        raise ValueError(f"{label} must be non-empty")
    return data


def release_members(firmware_path, font_path, font_root=FONT_ROOT):
    """Return canonical release members after validating all input files."""
    firmware_path = Path(firmware_path)
    if firmware_path.suffix.lower() != ".bin":
        raise ValueError("firmware must have a .bin filename")
    firmware_data = _regular_file(firmware_path, "firmware")
    font_data = _regular_file(font_path, "font")
    members = {
        firmware_path.name: firmware_data,
        "CN_BASIC.FNT": font_data,
        INSTALL_NAME: installation_text(firmware_path.name),
    }
    notice = Path(font_root) / "NOTICE.md"
    licenses = Path(font_root) / "licenses"
    if notice.is_symlink() or not notice.is_file() or not licenses.is_dir():
        raise ValueError("CN release notice or license directory is missing")
    members["NOTICE.md"] = notice.read_bytes()
    license_files = sorted(path for path in licenses.rglob("*") if path.is_file())
    relative_licenses = {path.relative_to(licenses).as_posix() for path in license_files}
    missing_licenses = sorted(REQUIRED_LICENSES - relative_licenses)
    if missing_licenses:
        raise ValueError("CN release is missing licenses: " + ", ".join(missing_licenses))
    for path in license_files:
        if path.is_symlink():
            raise ValueError(f"license must be a regular file: {path}")
        relative = path.relative_to(licenses).as_posix()
        members[f"licenses/{relative}"] = path.read_bytes()
    return members


def build_archive(font_data, release, members):
    """Validate the release contract and serialize a reproducible ZIP."""
    external_font.read_container(font_data)
    if len(font_data) != release.get("size"):
        raise ValueError("CN_BASIC.FNT release size mismatch")
    if sha256(font_data) != release.get("sha256"):
        raise ValueError("CN_BASIC.FNT release SHA256 mismatch")
    if members.get("CN_BASIC.FNT") != font_data:
        raise ValueError("release members contain a different CN_BASIC.FNT")
    firmware_names = [name for name, data in members.items()
                      if "/" not in name and name.lower().endswith(".bin") and data]
    if len(firmware_names) != 1:
        raise ValueError("release must contain exactly one non-empty firmware .bin")
    if "NOTICE.md" not in members or INSTALL_NAME not in members:
        raise ValueError("release notice or installation instructions are missing")
    if not any(name.startswith("licenses/") for name in members):
        raise ValueError("release contains no license files")
    if CHECKSUM_NAME in members:
        raise ValueError("SHA256SUMS.txt is generated by the packager")

    members = dict(members)
    members[CHECKSUM_NAME] = "".join(
        f"{sha256(members[name])}  {name}\n" for name in sorted(members)
    ).encode("utf-8")

    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_STORED) as archive:
        for name in sorted(members):
            if name.startswith("/") or ".." in Path(name).parts:
                raise ValueError(f"unsafe release member: {name}")
            info = zipfile.ZipInfo(name, FIXED_TIME)
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            info.compress_type = zipfile.ZIP_STORED
            archive.writestr(info, members[name])
    return output.getvalue()


def package(firmware_path, font_path, output_path, manifest_path=MANIFEST,
            font_root=FONT_ROOT):
    manifest = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
    release = manifest["external_font"]["release"]
    members = release_members(firmware_path, font_path, font_root)
    font_data = members["CN_BASIC.FNT"]
    data = build_archive(font_data, release, members)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(data)
    return data


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("firmware", type=Path, help="existing GX12 firmware .bin")
    parser.add_argument("font", type=Path, help="generated CN_BASIC.FNT")
    parser.add_argument("output", type=Path, help="release ZIP to create")
    args = parser.parse_args(argv)
    try:
        data = package(args.firmware, args.font, args.output)
    except (KeyError, OSError, ValueError, json.JSONDecodeError) as exc:
        parser.exit(1, f"error: {exc}\n")
    print(f"packaged {args.output}: bytes={len(data)} sha256={sha256(data)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
